package.json
src/components/cell/Cell.js
src/components/datatable/DataTable.context.js
src/components/datatable/DataTable.js
yarn.lock

- https://github.com/unfoldingWord/gateway-language-translation-suite/issues/37
- https://github.com/unfoldingWord/gateway-language-translation-suite/issues/38
- https://github.com/unfoldingWord/gateway-language-translation-suite/issues/44
(keep in mind rows are jumbled on purpose)
1. Filter to chapter 1, should display chip label properly.
2. Edit a cell.
3. Move Rows up and down.
4. Filter should persist and not reset.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/1)

Fix for persisting Filters, update MD-translatable

---

src/components/datatable/DataTable.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/4)

Scroll To Top

---

package.json
src/components/cell/Cell.js
src/components/column-filter/ColumnFilter.js
src/components/column-filter/helpers.js
src/components/column-filter/index.js
src/components/datatable/DataTable.context.js
src/components/datatable/DataTable.js
src/core/datatable.js
src/index.js
yarn.lock

Addresses #44 and #68
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/5)

Bugfix klappy filter options

---

src/components/datatable/DataTable.js
src/components/datatable/DataTable.md

To Test uncomment lines 11 - 14 to see the page change after receiving a new
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/6)

Fix New Resource Pagination

---

src/components/datatable/DataTable.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/7)

Fix For Filters ReRender On Cell Update

---

package.json
src/components/actions-menu/ActionsMenu.js
src/core/localStrings.js
yarn.lock

Tooltips for datatable-translatable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/8)

Feature cn tooltips

---

package.json
src/components/actions-menu/ActionsMenu.js
src/components/actions-menu/AddRow.js
src/components/actions-menu/DeleteRow.js
src/components/cell/Cell.js
src/components/datatable/DataTable.js
src/components/datatable/DataTable.md
src/core/datatable.js
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/9)

Scroll on Row Delete/Add

---

package.json
src/components/cell/Cell.js
src/components/datatable/DataTable.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/11)

Fix For Incorrect Row Index On Edit

---

src/components/cell/Cell.js
src/components/datatable/DataTable.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/12)

Remove Row Index Fix

---

package.json
src/components/datatable/DataTable.js
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/13)

Update MUI Tables Version

---

src/components/datatable/DataTable.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/14)

Fix OccurrenceNote not default for some files

---

src/components/actions-menu/AddRow.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/15)

Fix for #250 rowAdd duplicates ID field

---

package.json
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/18)

updated mui table

---

package.json
src/components/cell/Cell.js
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/20)

Early Fast Scrolling Fix

---

package.json
src/components/cell/Cell.js
src/components/datatable/DataTable.js
src/core/datatable.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/34)

Review jay 365 415

---

package.json
src/components/datatable/DataTable.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/31)

Fixed Expanded Scripture Pane Closing

---

src/core/datatable.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/29)

Fix Column Name Blank On Filter

---

src/components/toolbar/Toolbar.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/30)

Added QA aria-label for Preview and Save

---

package.json
src/components/datatable/DataTable.context.js
src/components/datatable/DataTable.js
styleguide.config.js
yarn.lock

Rolling back markdown-translatable
and adding in "good" fixes from along the way
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/36)

Rolling back markdown-translatable

---

.github/workflows/nodejs.yml
package.json
src/components/datatable/DataTable.js
src/components/datatable/DataTable.md
src/components/toolbar/Toolbar.js
src/components/toolbar/Toolbar.md
yarn.lock

This change is associated with tc-create-app#235, which is to add content validation to tc-create-app.
That "spike" covers adding content validation at several points:
- on open
- on save
- on blur (edit)
- on demand
This PR is solving for the last one, namely, "on demand". It adds an icon to the toolbar which invokes a new parameter specifying a validation function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/33)

Ready for Review/Merge

---

src/components/datatable/DataTable.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/38)

Fixed scrolling to top

---

src/components/cell/Cell.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/45)

added filters for zero width spaces U+200B

---

src/components/datatable/DataTable.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/41)

fix for when target file is shorter than source

---

__tests__/columnFilter.spec.js
package.json
src/components/column-filter/helpers.js
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/35)

Cannot read property split of undefined

---

src/core/datatable.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/49)

rm zwsp via regex

---

src/components/datatable/muiTheme.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/56)

TSV toolbar size

---

package.json
src/components/datatable/DataTable.context.js
src/core/datatable.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/58)

Zach merge 639 662

---

package.json
src/components/datatable/DataTable.context.js
src/core/datatable.js

Two odd things remain:
a) after undo delete is done, the new row remains at the end of the file instead of BCV order
b) when there are multiple deleted rows and when the last row is updated, then what ever field is updated that value will appear in the new last row. However, the row has no ID and is not really there... not sure how this happens...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/54)

[wip] Bug cn 639 deleted row edit

---

src/components/datatable/DataTable.js
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/68)

prompt on unsaved exit

---

src/components/actions-menu/ActionsMenu.js
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/66)

Omit row action menu for deleted rows

---

src/components/actions-menu/AddRow.js
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/67)

Removed text from dialog

---

src/core/datatable.js
yarn.lock

- ensure id begins with a letter
- ensure id is unique in the table
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/72)

Two fixes for ID Columns

---

src/components/actions-menu/AddRow.js
src/components/datatable/DataTable.context.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/75)

Fix dialog width from QA fail

---

package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/76)

bump v0.11.12

---

src/components/cell/Cell.js
src/components/datatable/DataTable.context.js
src/core/datatable.js

Had to make some changes that interfered with the Lossless TSV spec. Here is one change:
```js
const inputFilters = [[/<br>/gi, '\n'], [/^\u200B/,''], [/\u200B$/,''] ];
const outputFilters = [ [/^\u200B/,''], [/\u200B$/,''] ];
//const outputFilters = [[/\n/gi, '<br>'],[/^\u200B/,''], [/\u200B$/,''] ];
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/74)

Feature cn 788 impl tsv parser

---

package.json
src/components/actions-menu/ActionsMenu.js
src/components/datatable/DataTable.context.js
src/components/datatable/DataTable.js
src/components/datatable/DataTable.md
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/64)

autosave WIP

---

src/components/cell/Cell.js
src/components/cell/styles.js

this pr minimizes the white space in key value formate
.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/81)

WIP:Optimized use of space for TSV

---

src/components/cell/Cell.js

Implemented id for editable field in cell.js file for cypress test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/89)

Implemented id for editable field

---

src/components/datatable/DataTable.js
src/components/toolbar/Toolbar.js

added some id's to elements for eg: data-test="validate-icon", data-test="preview-icon", data-test="save-icon" in Toolbar.js file and added changes to options for a datatable (Datatable.js)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/84)

added some id's to elements and added changes to options for a datatable

---

.github/workflows/nodejs.yml
src/core/datatable.js

Fix github actions so they actually work.
Also includes a fix in the code so the tests pass. 
Updated the config slightly to use the latest versions
Also switched to ubuntu instead of macos because it finishes in 1 min instead of 3 mins.

Use latest lts node for testing

---

src/core/datatable.js

sorted chapter, verse and support reference

sorted chapter verse and supportreference

---

src/core/datatable.js

added back the sort function for the chapter and verse

Bugfix jincy 1312

---

src/components/datatable/DataTable.js
src/components/datatable/DataTable.md

- return to the last edited row when closing the search
- return to the last edited row when closing the filter

solved the issue 1088 and 1089

---

src/components/cell/Cell.js
src/components/cell/styles.js
src/components/datatable/DataTable.js
src/components/datatable/helpers.js

Used by unfoldingWord/tc-create-app#1407

Add prop to show custom fonts

---

package.json
src/components/column-filter/ColumnFilter.js
src/core/datatable.js

Bugfix for Filter selection is broken in TSV 7 for tN
steps to test 
1. select huge file for eg: GEN
2. select filter
3. select reference drop down 
so the fix would be like the
Also reduce the height of the dropdown

Bugfix for 1440

---

src/components/actions-menu/AddRow.js
src/components/cell/styles.js
src/components/datatable/DataTable.md
src/components/datatable/muiTheme.js

for #1513 and #1514
To Test
- scroll add new row in styleguidest 
- Window should scroll to new row and row should flash with a grew background for 3 secs.
- click on a field.
- Row should be highlighted and cell should be highlighted

Highlight current row and flash new row

---

src/components/datatable/muiTheme.js

https://github.com/unfoldingword/tc-create-app/issues/1514
Should look like this in styleguidst

Add border to selected row

---

src/components/actions-menu/ActionsMenu.js
src/components/actions-menu/AddRow.js
src/components/cell/HeaderCell.js
src/components/cell/styles.js
src/components/datatable/DataTable.js
src/components/datatable/helpers.js
src/components/datatable/muiTheme.js

https://github.com/unfoldingWord/tc-create-app/issues/1513
All rows should properly flash at once and the first editable cell will be focused.

Some tweaks to highlighting rows

---

src/components/column-filter/ColumnFilter.js

https://github.com/unfoldingWord/tc-create-app/issues/1522
Fixes issue clicking the x in the autocomplete field does not clear filter but make nothing show. 
Also fixes a warning that 'All' is not an option in the autocomplete options.

Properly clear filter

---

package.json
src/components/datatable/DataTable.js
src/components/datatable/DataTable.md
src/components/toolbar/Toolbar.js
yarn.lock

This add Extensible to the Toolbar

Add-extensible

---

package.json
src/components/actions-menu/AddRow.js
src/components/datatable/DataTable.js
src/core/datatable.js

This PR fixes the issue #1579 (https://app.zenhub.com/workspaces/tc-create-workspace-5f049cdbfa88090016bf043e/issues/gh/unfoldingword/tc-create-app/1579)

Bugfix jincy 1579

---

package.json

just a version update for issue 1579

just a version update for issue 1579

---

src/components/datatable/DataTable.js

- solved the issue [1395](https://github.com/unfoldingWord/tc-create-app/issues/1395)

Navigation to top & bottom while navigate to different page

---

src/components/datatable/DataTable.js

- Solved the issues [1606](https://github.com/unfoldingWord/tc-create-app/issues/1606) and [1607](https://github.com/unfoldingWord/tc-create-app/issues/1607)

Solved the issue 1606 and 1607

---

src/components/datatable/DataTable.js

- Added some CSS when navigating into the Row
- Solved the issues [1606](https://github.com/unfoldingWord/tc-create-app/issues/1606) and [1607](https://github.com/unfoldingWord/tc-create-app/issues/1607)

Solved: loses the blue frame around the record (1606 & 1607)

---

package.json
src/components/datatable/DataTable.js

- When the user adds or removes visible columns, changing TSV files or restarting the session, doesn't affect which columns are shown.
- Login into the app
- Select en_tn and book (eg: TIT)
- Click on the View column icon (Note only the rowHeader is clicked. In all books the rowheader will be default)
- click on the other columns checklist and change the book
- the selected columns remain the same for other books even if it doesn't effect after logout

Saved user choices for columns in TSV 
